### ISSUE TITLE
NPM package contains out-of-date helpers.d.ts

### ISSUE THREAD

**Issue by j-maas** [ktsn/vuex-type-helper#3]
When using the NPM version (which is three commits behind master), the [`helpers.d.ts`](https://github.com/ktsn/vuex-type-helper/blob/v1.1.0/helpers.d.ts#L1) contains a `require()`-style import.

In my setup this prevents the compilation. When I change it to an ES6-style import, as it is on [master](https://github.com/ktsn/vuex-type-helper/blob/master/helpers.d.ts#L1), it compiles.

Would it be possible to update the NPM package?

(By the way, I really love how straight forward this helper is to use!)

**Comment by ktsn** [comment]
Released v1.2.0

**Comment by j-maas** [comment]
What an amazing response time! Works like a charm.

Thanks for the work you have done! :)
