### ISSUE TITLE
Defining types for functions without arguments

### ISSUE THREAD

**Issue by rzane** [ktsn/vuex-type-helper#6]
When I define a mutation like this
```typescript
export interface User {
  id: number;
}

export interface AuthState {
  currentUser: User | null;
}

export interface AuthMutations {
  unsetCurrentUser: undefined;
}

const mutations: DefineMutations<AuthMutations, AuthState> = {
    unsetCurrentUser(state) {
      state.currentUser = null;
    }
}
```

Now, when I call the `unsetCurrentUser` mutation, I need to explicitly pass `undefined`. Is that necessary?

```typescript
mutations.unsetCurrentUser(state, undefined) // passes
mutations.unsetCurrentUser(state) // fails
```

**Comment by ktsn** [comment]
Since this lib was made before conditional types, it is needed to pass `undefined` explicitly for type safety. I guess we can omit that by defining the lib types with conditional types.

**Comment by rzane** [comment]
I really wanted to be able to enforce types a little better in my project, and based on your work, this is what I came up with: https://gist.github.com/rzane/51c1a462532acfa01296eb75f6830d10.

By using tuples, and declaring functions on my interfaces, I was able to solve this specific problem mentioned in this issue.

The interfaces that I define are a little different from the ones in the README. For example:

```typescript
interface AuthActions {
  login(user: User): Promise<void>;
}

interface AuthMutations {
  login(user: User): void;
  logout(): void;
}

interface AuthGetters {
  currentUser(): User | null;
}
```

Another cool thing offered in the gist are the helpers for components. It means that I also get type safety in components.

```typescript
class MyComponent extends Vue {
  @Getter currentUser!: UseGetter<'currentUser'>;
  @Action login!: UseAction<'login'>;
}
```

I'd be happy to send a PR based on my gist, if you are interested. I would be a breaking change for this library though.

**Comment by hirakuro** [comment]
Hello.
I faced similar case, and avoided the problem with code like below.

```
export interface AuthMutations {
  unsetCurrentUser: void;
}
mutations.unsetCurrentUser(state, undefined) // passes
mutations.unsetCurrentUser(state, null) // passes
mutations.unsetCurrentUser(state) // passes too
mutations.unsetCurrentUser(state, 0) // fails but it is expected
```

(Here is dummy code from yours because I can not publish our real code, sorry)

If you can accept  `mutations.unsetCurrentUser(state, undefined) // passes`, how about this work-around?

**Comment by hirakuro** [comment]
Sorry!
In a method of action with my work-around, I faced same problem too like below.

```
(snip)
  someAction({commit}){
    commit("unsetCurrentUser", undefined) // passses
    commit("unsetCurrentUser") // fails...
  }
```
